trigger:
  branches:
    include:
    - master

name:  $[format('{0:yyyyMMdd\-HHmmss}', pipeline.startTime)]

pool:
  vmImage: 'Ubuntu-16.04'

variables:
  CURRENT_DATE: $[format('{0:yyyyMMdd\-HHmmss}', pipeline.startTime)]
  REPOSITORY_NAME: $(Build.Repository.Name)
  COMMIT_TAG: $(git log --format=%h -1)

steps:
- script: |
     curl -L https://github.com/devkitPro/pacman/releases/download/devkitpro-pacman-1.0.1/devkitpro-pacman.deb -o pacman.deb
     sudo apt update
     sudo apt install p7zip-full haveged
     sudo dpkg -i pacman.deb
     sudo dkp-pacman -Sy
     sudo dkp-pacman -S 3ds-dev --noconfirm
     sudo dkp-pacman -S 3ds-curl 3ds-libarchive 3ds-liblzma 3ds-mbedtls 3ds-bzip2 3ds-zlib 3ds-sdl 3ds-sdl_mixer 3ds-mpg123 --noconfirm
     sudo 7z x libctru.7z -o/opt/devkitpro/ -y
     curl -L https://github.com/Steveice10/bannertool/releases/download/1.1.0/bannertool.zip -o bannertool.zip
     sudo 7z e bannertool.zip linux-x86_64/bannertool
     sudo chmod +x bannertool
     rm bannertool.zip
     curl -L https://github.com/profi200/Project_CTR/releases/download/0.15/makerom_015_ctrtool.zip -o makerom_015_ctrtool.zip
     sudo 7z e makerom_015_ctrtool.zip Linux_x86_64/makerom
     sudo chmod +x makerom
     rm makerom_015_ctrtool.zip
  displayName: 'Setup devkitPro'
  
- script: |
     export PATH=$PATH:$(pwd)
     export DEVKITPRO="/opt/devkitpro"
     export DEVKITARM="/opt/devkitpro/devkitARM"
     make
  displayName: 'Build Universal-Updater'

- script: |
    echo '##vso[task.setvariable variable=COMMIT_TAG]'$(git log --format=%h -1)
    echo '##vso[task.setvariable variable=COMMIT_MESSAGE]'$(git log --pretty=format:"%an - %s" -1)
    git config --global user.email "flamekat54@aol.com"
    git config --global user.name "TWLBot"
    git clone https://$GITHUB_TOKEN@github.com/TWLBot/Builds.git
    cd Builds/extras
    cp ../../Universal-Updater.3dsx Universal-Updater.3dsx
    cp ../../Universal-Updater.cia Universal-Updater.cia
    git stage .
    git commit -m "Universal-Updater | $(COMMIT_TAG)"
    git push origin master
    git tag v$CURRENT_DATE
    echo '##vso[task.setvariable variable=TWLBOT_COMMIT]'$(git log -1 --format="%H")
  displayName: "Commit to TWLBot/Builds"

- task: GitHubRelease@0
  displayName: "Release to TWLBot/Builds"
  inputs:
    gitHubConnection: TWLBot
    repositoryName: TWLBot/Builds
    action: create
    target: $(TWLBOT_COMMIT)
    tagSource: 'manual'
    tag: v$(CURRENT_DATE)
    title: Universal-Updater | $(COMMIT_TAG)
    releaseNotesSource: input
    releaseNotes: $(COMMIT_MESSAGE)
    assets: '$(Build.ArtifactStagingDirectory)/*'
    isPreRelease: true
    addChangeLog: false
    
# I needed a new branch to test stuffs on
